name: MilkNet CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # Remove 22.x since it's still in development and may have compatibility issues

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install nth-check@2.0.1
          npm install serialize-javascript@6.0.2
          npm install cookie@0.7.0
          npm install svgo@3.0.2
          npm install postcss@8.5.3

      - name: Build
        run: npm run build
        env:
          CI: false # Prevent treating warnings as errors
          REACT_APP_SEPOLIA_CONTRACT_ADDRESS: ${{ secrets.REACT_APP_SEPOLIA_CONTRACT_ADDRESS }}

      - name: Run tests
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results
